// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqyzyngrgshqsyambhwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxeXp5bmdyZ3NocXN5YW1iaHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDY4MzYsImV4cCI6MjA1MDEyMjgzNn0.7Z2rhxIbBPEEKenxTTMLzqU2ciqUVIgNg6CQpRXGMn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);